# Generated by Django 5.0.3 on 2024-04-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HangManGame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
