# Generated by Django 5.0.3 on 2024-04-01 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HangManGame', '0002_game_player_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='player_name',
        ),
    ]
