# Generated by Django 5.0.3 on 2024-04-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HangManGame', '0003_remove_game_player_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='incorrect_guesses_allowed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
